#!/bin/bash

TESTNAME=$1
shift

which iverilog &> /dev/null
if [ "$?" == "0" ]; then
 iverilog -f bridge.vf tests/$TESTNAME.v $*
 ./a.out
else
 vcs -full64 +v2k -R -I -f bridge.vf tests/$TESTNAME.v $*
fi

